stages:
  - deploy
  - run

build and push image:
  stage: deploy
  only:
    - master
  image: docker:1.11
  services:
    - docker:dind
  script:
    # NOTE(krish): this is the only way i found to get commit count but it always gives 50!
    - apk update && apk add git
    - COMMIT_COUNT=$(git rev-list --count HEAD)
    - echo $COMMIT_COUNT
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:latest everysize
    # - docker tag $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:$COMMIT_COUNT
    - docker push $CI_REGISTRY_IMAGE:latest # $CI_REGISTRY_IMAGE:$COMMIT_COUNT

run on freebox:
  stage: run
  image: debian:buster-slim
  before_script:
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "${FREEBOX_SSH_KEY}" | ssh-add -
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh $FREEBOX_USER@$FREEBOX_URL "
        cd ~/Projects/$CI_PROJECT_NAME &&
        git reset --hard HEAD &&
        git pull &&
        ./run.sh
      "
